on: [push]
jobs:
  docker-img:
    name: Create docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: rlespinasse/github-slug-action@v3.x
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/fa2k/lys/lys:latest
          cache-from: type=registry,ref=${{ ghcr.io/fa2k/lys/lys:latest }}
          cache-to: type=inline

